[workspace]
members = ["bulb-core", "bulb-app", "bulb-vst"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0.100"
rust-async-tuyapi = "1.0.0"
serde_json = "1.0"
