[package]
name = "bulb-vst"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bulb-core = { path = "../bulb-core" }
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
tokio = { workspace = true }
crossbeam-channel = "0.5"
